apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: project-role
  namespace: default

rules:
  # Pods
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

  # Pod logs
  - apiGroups: [""]
    resources:
      - pods/log
    verbs:
      - get

  # Services
  - apiGroups: [""]
    resources:
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # PersistentVolumeClaims
  - apiGroups: [""]
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # ConfigMaps
  - apiGroups: [""]
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Deployments
  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
   # EndPoints
  - apiGroups: [""]
    resources:
      - endpoints
    verbs:
      - get
      - list
      - watch
      
